-- 코드를 입력하세요

SELECT FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM (
        SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER FROM JULY
    ) AS Combined
    GROUP BY FLAVOR
) AS CombinedTotal
ORDER BY TOTAL DESC
LIMIT 3;