-- 코드를 입력하세요
SELECT B.CATEGORY AS CATEGORY
     , SUM(SALES) AS TOTAL_SALES
FROM BOOK AS B
    INNER JOIN BOOK_SALES AS BS ON B.BOOK_ID = BS.BOOK_ID
WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY